# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the container
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN --mount=type=cache,target=/root/.npm pnpm install --frozen-lockfile

# Copy source files
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Stage 2: Run the application
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist ./dist
COPY package.json .

# Install only production dependencies
RUN pnpm install --prod --frozen-lockfile

# Command to run the application
CMD ["node", "dist/index.js"]
